### ISSUE TITLE
TODO -> Project Ideas

### ISSUE THREAD

**Issue by jd-apprentice** [jd-apprentice/PlatziRPC#2]
## General Ideas
- [x] Scrapping for the course name
- [ ] Hide bash when running the app
- [ ] Track how much time is left for a course instead of running a general timer
- [x] Migrate to TS

**Comment by jd-apprentice** [comment]
- [x] Scrapping for the course name -> has been done in PR #4

**Comment by jd-apprentice** [comment]
- [x] Migrate to TS #5
